@baseUrl = http://localhost:3001/api

### List all persons

{{baseUrl}}/persons

### Get a single person

{{baseUrl}}/persons/5ed7b070be873d049befd651

### Create a new person

POST {{baseUrl}}/persons
Content-Type: application/json

{
    "name": "Test User 1",
    "number": "555-555-5555"
}

### Update an existing person

PUT {{baseUrl}}/persons/5ed7b070be873d049befd651
Content-Type: application/json

{
    "name": "ben2",
    "number": "555-555-5555"
}


### Delete a person

DELETE {{baseUrl}}/persons/5ef5014e60f744120128c359